services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: observability
      POSTGRES_USER: obs_user
      POSTGRES_PASSWORD: obs_pass
    ports:
    - '5432:5432'
    volumes:
    - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - '6379:6379'
      
  api:
    build: ./api-node
    ports:
      - '3000:3000'
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: observability
      POSTGRES_USER: obs_user
      POSTGRES_PASSWORD: obs_pass
      REDIS_HOST: redis
    depends_on:
      - postgres
      - redis

  analytics:
    build: ./analytics-python
    depends_on:
      - postgres

volumes:
  pgdata: